# Generated by Django 4.0 on 2022-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogscontent',
            name='blogs_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
